server:
  port: 5010

camunda.bpm:
  history-level: none
  generic-properties.properties:
    telemetry-reporter-activate: false
  auto-deployment-enabled: false
  generic-properties:
    properties:
      enforceHistoryTimeToLive: false
      enableDefaultDbHistoryEventHandler: false
acko:
  rap-manager-service:
    url: https://health-rap-manager-service-uat.internal.ackodev.com
  tool-name:
    name: Doc_tool
management:
  endpoint:
    health:
      show-details: "ALWAYS"
--- 
spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: b-2.sureosackodevmsk.spoc7n.c3.kafka.ap-south-1.amazonaws.com:9094,b-1.sureosackodevmsk.spoc7n.c3.kafka.ap-south-1.amazonaws.com:9094,b-3.sureosackodevmsk.spoc7n.c3.kafka.ap-south-1.amazonaws.com:9094
    max.request.size: 10485880
    security:
      protocol: SSL
    consumer:
      security:
        protocol: SSL
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.acko.tool.serializer.KafkaMessageSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/acko_tool?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      port: 27017
      database: acko_tool
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyRealm
          jwk-set-uri: http://localhost:8080/realms/MyRealm/protocol/openid-connect/certs
  elasticsearch:
    uris: http://localhost:9200

acko:
  rap-manager-service:
    url: https://health-rap-manager-service-uat.internal.ackodev.com
  tool-name:
    name: Doc_tool

jwt:
  auth:
    converter:
      resource-id: my-client
      principal-attribute: preferred_username

elasticsearch:
  url: http://localhost:9200
  taskIndex: tasks
  userIndex: user
  eventIndex: event

keycloak:
  serverUrl: http://localhost:8080
  realm: master
  clientId: admin-cli
  adminUserName: admin
  adminPassword: admin

--- 
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql_container:3306/camunda
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/acko_tool?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      port: 27017
      database: acko_tool
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/MyRealm
          jwk-set-uri: http://keycloak:8080/realms/MyRealm/protocol/openid-connect/certs
  elasticsearch:
    uris: http://elasticsearch:9200

jwt:
  auth:
    converter:
      resource-id: my-client
      principal-attribute: preferred_username
          

elasticsearch:
  url: http://elasticsearch:9200
  taskIndex: tasks
  userIndex: user
  eventIndex: event

keycloak:
  serverUrl: http://keycloak:8080
  realm: master
  clientId: admin-cli

acko:
  rap-manager-service:
    url: https://health-rap-manager-service-uat.internal.ackodev.com

management:
  endpoint:
    health:
      show-details: "ALWAYS"


  adminUserName: admin
  adminPassword: admin

