server:
  port: 5010

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/acko_tool?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      port: 27017
      database: acko_tool
      auto-index-creation: true
