server:
  port: 5010

spring:
  datasource:
    url: jdbc:mysql://mysql_container:3306/camunda
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/acko_tool?retryWrites=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1
      port: 27017
      database: acko_tool
      auto-index-creation: true

camunda.bpm:
  history-level: none
  generic-properties.properties:
    telemetry-reporter-activate: false
  auto-deployment-enabled: false
  generic-properties:
    properties:
      enforceHistoryTimeToLive: false
      enableDefaultDbHistoryEventHandler: false

elasticsearch:
  url: http://localhost:9200
  index: task

keycloak:
  serverUrl: http://localhost:8080
  realm: master
  clientId: admin-cli
  userName: admin
  password: admin
